### ISSUE TITLE
Cara run bot di replit 

### ISSUE THREAD

**Issue by botstylee** [moo-d/termux-whatsapp-bot#5]
Bruh gw mau nanya cara install modul imagemagick ffmpeg dan libwebp di replit gimana si masa gw gagal Mulu gak kebaca modul yg udh gw install tadi

**Comment by moo-d** [comment]
Kamu tidak akan bisa menginstall package di `Replit`. Karena `Replit` akan langsung import package melalui file.
Contoh:
```js
const fs = require('fs')
```
Package `fs` akan langsung ada di `Replit`.

**Comment by moo-d** [comment]
FFmpeg dihapus dari `repl.it`,  kusaranin jangan pake replit

**Comment by botstylee** [comment]
> Dengan Replit, Anda dapat menggunakan sebagian besar paket yang tersedia dalam Python dan JavaScript. Replit akan menginstal banyak paket dengan cepat hanya dengan mengimpornya dalam kode.
> 
> ### Direct Imports
> ```js
> const express = require('express');
> ```
> 
> Melakukannya akan menginstal versi terbaru dari paket ke repl Anda. File spesifikasi dan file kunci akan dibuat sehingga versi tidak akan berubah. Jika memungkinkan, sebaiknya gunakan file untuk mengelola dependensi.

Iye gw tau tapi cara install modul imagemagick sama ffmpeg gimana biar kebaca

**Comment by botstylee** [comment]
![Screenshot_2021-10-01-17-00-58-50_2768c6f3dd71c987876b7b9730ce2453](https://user-images.githubusercontent.com/85060672/135600800-08e474aa-5bba-465e-9f54-e1f5a192b092.png)
Gak kebaca tuh modul imagemagick sama ffmpeg aneh banget

**Comment by moo-d** [comment]
> ![Screenshot_2021-10-01-17-00-58-50_2768c6f3dd71c987876b7b9730ce2453](https://user-images.githubusercontent.com/85060672/135600800-08e474aa-5bba-465e-9f54-e1f5a192b092.png) Gak kebaca tuh modul imagemagick sama ffmpeg aneh banget

Maaf, Repl.it tidak mendukung `FFmpeg` lagi. Awalnya digunakan untuk bot dan spam, jadi mereka menghapus fungsinya.
