### ISSUE TITLE
Tolong saya

### ISSUE THREAD

**Issue by JefIra24** [moo-d/termux-whatsapp-bot#7]
~/baileys-wabot $ bash install.sh
Hit:1 https://mirror.bardia.tech/termux/termux-packages-24 stable InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  openssl-1.1
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[Installing Package]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (5.0.1-2).
libwebp is already the newest version (1.2.2).
nodejs is already the newest version (18.4.0).
tesseract is already the newest version (5.1.0-3).
wget is already the newest version (1.21.3-2).
The following package was automatically installed and is no longer required:
  openssl-1.1
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2022-07-20 11:13:46--  https://github.com/tesseract-ocr/tessdata/blob/master/ind.traineddata?raw=true
Resolving github.com... 20.205.243.166
Connecting to github.com|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/tesseract-ocr/tessdata/blob/main/ind.traineddata [following]
--2022-07-20 11:13:47--  https://github.com/tesseract-ocr/tessdata/blob/main/ind.traineddata
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’

      /data/            0  --.-KB/s             /data/data/c      136.25K   800KB/s    in 0.2s  

2022-07-20 11:13:48 (800 KB/s) - ‘/data/data/com.termux/files/home/../usr/share/tessdata/ind.traineddata’ saved [139522]

[Installing Dependencies]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > sharp@0.30.5 install
npm ERR! > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR!
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-android-arm64v8.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN skipping integrity check for git dependency ssh://git@github.com/adiwajshing/libsignal-node.git
npm ERR! npm WARN skipping integrity check for git dependency ssh://git@github.com/adiwajshing/eslint-config.git
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for android-arm64v8
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/git-clonewRmbZh/node_modules/sharp
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-07-20T04_14_49_783Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-07-20T04_13_52_317Z-debug-0.log
[*] All dependencies have been installed, please run the command "npm start" to immediately start the script

**Comment by moo-d** [comment]
Oh, sc ini udh mati... Untuk yg terbaru ada di [sini](https://github.com/moo-d/inos-baileys-wabot)
